### ISSUE TITLE
error: Value of type 'WebSocket' has no member 'bufferedBytes'

### ISSUE THREAD

**Issue by zhwIdea** [Local-Connectivity-Lab/lcl-speedtest#4]
After referencing through swift package Dependencies, the project is compiled and an error is reported
error: Value of type 'WebSocket' has no member 'bufferedBytes'

**Comment by johnnzhou** [comment]
Hi, 

thanks for the issue. Can you try the latest main or version [1.0.0](https://github.com/Local-Connectivity-Lab/lcl-speedtest/releases/tag/1.0.0)? The issue should be resolved.

**Comment by johnnzhou** [comment]
Hi @zhwIdea, sorry for the delay and the inconvenience. The latest version should resolve the compilation issue. I will close this issue for now. If you see the issue reappear, feel free to reopen this issue.
